server:
  port: 8090
  address: 0.0.0.0

spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    baseline-on-migrate: false

management:
  endpoints:
    web:
      base-path: /api
      exposure:
        include: health, info
  endpoint:
    health:
      roles: ADMIN
      show-details: when_authorized

exercisedb:
  api-url: https://exercisedb.p.rapidapi.com
  api-key: ${EXERCISEDB_API_KEY:}
  api-host: exercisedb.p.rapidapi.com


